#!/bin/bash
BATTERY=(         )
PC=$(acpi | awk '{print $4}' | tr -d '%,')
INDEX=$(echo "$PC/20.1" | bc)
STATUS=$(acpi | awk '{print $3}' | tr -d ',')
if [[ $STATUS = "Charging" ]]; then
    INDEX=$(echo $(date +%s) % 5 | bc)
    C=""
    echo $PC"% "${BATTERY[$INDEX]}"  "${C}
    exit
fi
echo $PC"% "${BATTERY[$INDEX]}
